name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: download
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}
          git pull --rebase
          chmod +x ./bin/yt-dlp
          ./bin/yt-dlp --config-locations config
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: download.zip
          path: download/
